name: Release Build

on:
  release:
    types: [created]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Triggered by: ${{ github.event.action }}"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make test script executable
        run: chmod +x ./test.sh

      - name: Run test script
        run: ./test.sh

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Make build script executable
        run: chmod +x ./build.sh
      
      - name: Run build script
        run: ./build.sh
      
      - name: Upload minified script
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sycamore.min.sh
            sycamore-completion.min.bash
